### ISSUE TITLE
extensions that are not web-packed do not have node_modules folder included in the vsix

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#21017]
This is not caused by recent merge.

e.g. Import extension.

**Comment by alanrenmsft** [comment]
fixed by Aasim.

**Comment by Charles-Gagnon** [comment]
Link to the PR that fixed this?

**Comment by alanrenmsft** [comment]
https://github.com/microsoft/azuredatastudio/pull/21391

**Comment by Charles-Gagnon** [comment]
Ah, but this doesn't really fix the actual issue (node_modules missing) - right? If we add another extension that isn't webpacked it would still have the same issue?

(not that we should be having non-webpacked extensions. Just wanted to clarify for future reference)

**Comment by alanrenmsft** [comment]
hmm, you are actually right, I am going to leave this issue open.
