### ISSUE TITLE
A11y_SQLdatabase projects extension_View And More Action_Create Project From Database_Usability: Tooltip information is not provided for browse button.

### ISSUE THREAD

**Issue by SachinChavhan317** [microsoft/azuredatastudio#22161]
### GitHub Tags
#A11yMAS; #A11ySev4; #A11yTCS; #DesktopApp; #SH-SQL Azure Data Studio-MAC-March23; #SQL Azure Data Studio; #A11yUsable; #MAC; #AINotInScope;

### Environment Details
Application Name: SQL Azure Data Studio
Version: 1.41.2 (user setup)
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621
Screen reader: NVDA

### Repro Steps

1. Launch Azure Data Studio
2. Tab till extension and search for “SQL Database Projects” and install it.
3. Tab till database project and press enter. “Database Project” panel will open.
4. Tab till “View and More Action” button and press enter.
5. Tab till “Create Project from Database” and press enter.
6. Verify whether the tooltip is provided for browse button or not.

### Actual Result:​
On keyboard focus tooltip information is not provided for browse button.

### Expected Result:​
Tooltip information should be provided for browse button.

### User Impact:
Keyboard users will face difficulties in knowing the control functionality if tooltip is not provided for browse button.

### Attachment:
![Presentation1](https://user-images.githubusercontent.com/86241494/223086945-6146649f-d07c-41d0-ae11-693db6cf0a45.gif)

**Comment by kisantia** [comment]
@SachinChavhan317 this has been fixed in the latest version of the sql database projects extension (0.23.0). Please download the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and verify this is fixed. Thanks!

**Comment by kisantia** [comment]
@SachinChavhan317 Please verify this issue is fixed.

**Comment by kisantia** [comment]
@SachinChavhan317 please verify this has been fixed and close the issue 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/4c0a5896-ea0e-4b5c-9e2d-f40635a625da)

**Comment by SachinChavhan317** [comment]
#Regressed:09-25-23;
Verified the bug on below version,

Version: 1.47.0-insider (Universal)
Commit: https://github.com/microsoft/azuredatastudio/commit/a63463e35bb21bb89250be09d9639ff440c83b39
Date: 2023-09-21T05:42:38.696Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

The issue is still reproducing. 
[kisantia](https://github.com/kisantia) Could you please provide the build details in which fixes are available. Thanks.

<img width="1440" alt="Screenshot 2023-09-25 at 5 24 58 PM" src="https://github.com/microsoft/azuredatastudio/assets/86241494/53ed8e53-edd9-42fc-b284-db5f363c4691">
