### ISSUE TITLE
A11y_SQLdatabase projects extension_Advance Publish_Publish Option_Usability: Tooltip information is not provided for "Select connection" button.

### ISSUE THREAD

**Issue by AnKushSingh05** [microsoft/azuredatastudio#22219]
### GitHub Tags
#A11yTCS; #A11ySev4; #DesktopApp; #Win11; #SH-SQL Azure Data Studio-Win32-March23; #Win32; #SQL Azure Data Studio; #A11yUsable; 

### Environment Details:
Application Name: SQL Azure Data Studio
Version: 1.41.2 (user setup)
Microsoft Windows 11 Enterprise 10.0.22621 Build 2262

### Repro Steps:

1. Launch Azure Data Studio
2. Tab till extension and search for “SQL Database Projects” and install it.
3. Tab till database project and press enter.
4. “Database Project” panel will open.
5. Tab till “View And More Action” button and press enter.
6. Tab till “Create Project From Database” and press enter.
7. Tab till server field and press enter.
8. “Connection” dialog will open. Fill the details for SQL server and connect.
9.  Tab till Create button and press enter.
10. Database project will get create and will appear in Database project pane
11. Tab till created project name in Database Project panel.
12. Press context menu button(right click).
13. Tab till Publish and press enter.
14. Publish Project window will open.
15. Tab till “Advance” button and press enter.
16. Tab till Publish Option tab and press enter.
17. Verify whether the Tooltip information is provided for "Select connection" button or not.

### Actual Result:​
On keyboard focus tooltip information is not provided for "Select connection" button.

### Expected Result:​
Tooltip information should be provided for "Select connection" button.

### User Impact:
Keyboard users will face difficulties in knowing the control functionality if tooltip is not provided for Select connection button.

### Attachment:
![Tooltip](https://user-images.githubusercontent.com/124244478/223642098-1616822c-b9e7-47da-ab2d-558419514354.gif)

**Comment by kisantia** [comment]
@AnKushSingh05 this has been fixed in the latest version of the sql database projects extension (0.23.0). Please download the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and verify this is fixed. Thanks!

**Comment by AnKushSingh05** [comment]
Regressed the issue in the below environment.
Version: 1.43.0-insider (user setup)
Commit: afafee844ce2b07eb55bdb6f40ee1ce88c0bbf4e
Date: 2023-03-29T05:28:54.263Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

Issue is still not fixed. 
Tooltip is only accessible with the mouse not with the keyboard. It should be accessible with the keyboard also
![Bug_22219_Not Fixed](https://user-images.githubusercontent.com/124244478/229019826-15731f85-4c14-4d58-8ee9-c99721a1444a.gif)
.

**Comment by kisantia** [comment]
this is an external issue and we already have an issue tracking this in ADS: https://github.com/microsoft/azuredatastudio/issues/19566
