### ISSUE TITLE
Intellicode error shown upon launch

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#22323]
Issue Type: <b>Bug</b>

When launching ADS, an error activating Intellicode is shown.

```
Sorry, something went wrong activating IntelliCode support for SQL. Please check the "MSSQL" and "VS IntelliCode" output windows for details.
```

```
[2023-03-14 14:05:24.545] [exthost] [info] Extension host with pid 23196 started
[2023-03-14 14:05:24.621] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.xml-language-features, startup: false, activationEvent: 'onLanguage:sql'
[2023-03-14 14:05:24.633] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:sql'
[2023-03-14 14:05:24.763] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.azurecore, startup: true, activationEvent: '*'
[2023-03-14 14:05:27.394] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2023-03-14 14:05:27.404] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2023-03-14 14:05:27.415] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.mssql, startup: true, activationEvent: '*'
[2023-03-14 14:05:27.491] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.notebook, startup: true, activationEvent: '*'
[2023-03-14 14:05:27.963] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2023-03-14 14:05:27.993] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2023-03-14 14:05:30.233] [exthost] [info] Eager extensions activated
[2023-03-14 14:05:30.243] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2023-03-14 14:05:30.417] [exthost] [error] Error: Could not load type 'Microsoft.SqlTools.Utility.Logger' from assembly 'Microsoft.SqlTools.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:694018
	at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:694312
	at Immediate.<anonymous> (c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:694673)
	at process.processImmediate (node:internal/timers:466:21) mssql.loadCompletionExtension {"value":"Microsoft.mssql","_lower":"microsoft.mssql"}
[2023-03-14 14:06:44.973] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
```

Intellicode Output tab:
```
Acquiring model 'intellisense-members' for sql
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-SQL was passed a model: {"modelPath":"c:\\Users\\jtsombakos\\.azuredatastudio-insiders\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.1\\cache\\99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C","modelId":"99136CA159AB897D942412E976015B8C9EC2","outputId":"6D6727BA7E6347BE9124EF572943AC5C"}.
Error while activating SQL: {"code":0,"data":null}
```

Azure Data Studio version: azuredatastudio-insiders 1.43.0-insider (ef99e67cfe16ba993ccec2de266c5f973492e5de, 2023-03-14T05:32:31.464Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (15.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.13.0
import|Mic|1.5.4
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.22.0
sql-search|Red|0.4.0
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment]
@jtsom are you also seeing this issue on the latest state build or only on insiders build?  The error says one of the core SQL Tools Service assemblies couldn't load, which is most commonly an error during installation that should be repaired by reinstall.

**Comment by LarnuUK** [comment]
@kburtram I am facing this problem on latest state build. I have reinstalled and I am stiill getting the same error as the OP shows:
```none
Acquiring model 'intellisense-members' for sql
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-SQL was passed a model: {"modelPath":"c:\\Users\\Larnu\\.azuredatastudio\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.1\\cache\\99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C","modelId":"99136CA159AB897D942412E976015B8C9EC2","outputId":"6D6727BA7E6347BE9124EF572943AC5C"}.
Error while activating SQL: {"code":0,"data":null}
````

**Comment by VizWiz311** [comment]
Same here with 1.42.0

**Comment by atxaloisio** [comment]
Same here with 1.42.0

**Comment by kburtram** [comment]
This appears related to changes made in the SQL Tools Service component in 1.42 that are fixed by the linked PR.  We'll have the fix in insiders build once that's merged over into ADS.

For additional context this is the error shown on ADS startup.

![image](https://user-images.githubusercontent.com/599935/227637028-7692afdc-9c1d-4aaa-afff-73984e2472f5.png)

**Comment by alienBear** [comment]
I am also seeing this issue in 1.42.0.

**Comment by kburtram** [comment]
Closing based on above comments.  The fix will be included in the next stable release planned for April 12th.

**Comment by pfab0** [comment]
This issue is still occurring in 
Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)

https://github.com/MicrosoftDocs/intellicode/issues/469

**Comment by cheenamalhotra** [comment]
@pfab0 Can you please open a new issue in this repo with logs attached?
Ref: [How to set the logging level](https://learn.microsoft.com/en-us/sql/azure-data-studio/troubleshooting?view=sql-server-ver16#how-to-set-the-logging-level)
