### ISSUE TITLE
Query hangs for Synapse Dedicated Pool

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23400]
Version: 1.45.0-insider (user setup)
Commit: 7a7a38dd246ea81f848374368fba8686ac6f79d4
Date: 2023-06-16T05:39:07.252Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

I've updated to 1.44.1 and get the same issue - it happens so frequently that it takes no time at all to reproduce the issue.  I didn't change connection and I had no error/warning outstanding - it just hangs when you run the query.  The execution time doesn't start moving either - it's like it's doing some kind of pre-execution check and gets stuck.  What's interesting is I can just repeatedly run the same piece of SQL in the same connection and get the issue every few times.

_Originally posted by @MikePittAge in https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1594774911_
            
I've stayed on v. 1.39.1, where there's the occasional inexplicable 10+ second wait (accessing an older SQL Server 2008 via VPN) - after encountering the full hang up (requiring application restart) too many times on later versions. I also have Insider installed, but have resorted back to sticking with an older version until this gets cleared up. (Otherwise, as clunky as it is, I'd be better off using MS SQL SMS.)

_Originally posted by @Ben-CA in https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1594806765_
         
Log for investigation: 
[QueryHang_dedicatedPool.txt](https://github.com/microsoft/azuredatastudio/files/11771873/QueryHang_dedicatedPool.txt)

Observation:
The query editor hangs for 40+ seconds (column dependent) and when done loading metadata seems to execute in 1 second.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/e477f74f-47e9-4884-9a99-9ef0a978c71c)

**Comment by wospl** [comment]
Any ETA about the resolution of this issue?

**Comment by erinstellato-ms** [comment]
@wospl This is something we'll be looking into in the next few weeks.  Thanks for checking in, I promise we haven't forgotten about it and are committed to finding a solution.

**Comment by cheenamalhotra** [comment]
Hi @wospl @Ben-CA @MikePittAge

Would request you to try out the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know how it goes!
The issue with blocking metadata collection has been fixed.

Version: 1.46.0-insider (user setup)
Commit: 8c988623431f875fb4ae0049d72c94faf8eb7123
Date: 2023-08-24T17:23:12.287Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Thanks! :)

**Comment by Ben-CA** [comment]
@cheenamalhotra I've updated to the latest insider build this morning, and I'll see how it works. Thanks

**Comment by Ben-CA** [comment]
I've been using it some today without any major hangs - showing promise!

**Comment by cheenamalhotra** [comment]
I will proceed to close this as resolved, please let us know if you experience any unexpected hangs with Synapse again.

**Comment by wospl** [comment]
Hello, the problem is still present. I'm connected to an Azure SQL pool.

Version: 1.46.0-insider (system setup)
Commit: bf6701dbdfe066f631bc97c919048e0cc37c9fd2
Date: 2023-08-28T05:45:18.512Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Thank you!

**Comment by cheenamalhotra** [comment]
@wospl Can you provide more detail on what is the issue you're facing?

This issue was tracking intermittent hangs when executing simple queries that should not normally get stuck and take long time.

**Comment by wospl** [comment]
> @wospl Can you provide more detail on what is the issue you're facing?
> 
> This issue was tracking intermittent hangs when executing simple queries that should not normally get stuck and take long time.

I launched a malformed query. The timer of SQL exeuction was stuck at 0 and, after 2 minutes, it was still hanging. I closed Azure Data Studio and reopened to work around. Let me know if you need more detail such that I can collect them the next time the issue arises. Thank you!

**Comment by Ben-in-CA** [comment]
Well, I just had a hang on Insiders; posted it to here instead: https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1701416145

**Comment by wospl** [comment]
> Does it also occur in stable release? Can you share the malformed query that I can run to reproduce the issue?

It seems that the problem is not "regular". If I restart ADS, connect to the SQL and run again the query, it works. It seems to me that it happens with different types of queries (malformed or wellformed, big or little). As of now I don't have any query to send, but the point is that it could not matter.

**Comment by cheenamalhotra** [comment]
Ok, I'd request you to keep capturing [MSSQL verbose logging](https://github.com/microsoft/azuredatastudio/wiki/Debug-Trace-Logging#mssql), so if you do face this again, logs can be fetched, and you can upload them in a new issue.
