### ISSUE TITLE
Recent connection DOESN'T change TAB colors in according with server-group colors settings

### ISSUE THREAD

**Issue by jakodev** [microsoft/azuredatastudio#24098]
Azure Data Studio Version: 1.45.1
OS: Windows_NT x64 10.0.19045
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:42:37.945Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0

Hi, since v1.45.00 I'm experiencing the issue described in the TITLE. I was hoping with the next release this will be fixed, but it is not, so I'm here

Steps to Reproduce:

I'm using 4 Server-Group with 4 different colors (DEV, PRODUCTION, TEST, DEMO)

1. Clean Recent Connection
2. Choose one connection from saved connections list
3. Switch to another connection but organized in different server-group (identified by a different color)
4. The TAB color change in according with server-group colors setting (As Expected! VERY GOOD)
5. Now switch to another connection but choosing from **Recents Connection**
6. The TAB color maintain the same previuos color, so that means NO CHANGE in according to the choosed server-group (VERY BAD)

This bug seems tiny but is potentially very dangerous, what if I run a script in production environment thinking I was in development due to wrong color TAB?

Please, fix it quickly
 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by cheenamalhotra** [comment]
Hi @jakodev 

The issue https://github.com/microsoft/azuredatastudio/issues/23996 has been fixed in the insiders build, and will be included in the Sept release.
You can use the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) to get the fix.

**Comment by Rob-DeRosia** [comment]
I agree with @jakodev on this. The tab colors are really helpful to know which environment you're working in. Without the colors, **the tool is requiring extra, tedious work** to confirm your connection before executing any query. 

The sooner this can be released, the happier the colored-tab users will be.

**Comment by jakodev** [comment]
> Hi @jakodev
> 
> The issue #23996 has been fixed in the insiders build, and will be included in the Sept release. You can use the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) to get the fix or use Browse > Saved connections instead.
> 
> > This bug seems tiny but is potentially very dangerous, what if I run a script in production environment thinking I was in development due to wrong color TAB?
> 
> From investigations, it's the tab color that doesn't get updated, the underlying connection is updated as expected.

Thank you very much! 👍

**Comment by cheenamalhotra** [comment]
I'll close this issue as resolved, since the fix has been made in insiders.

**Comment by Rob-DeRosia** [comment]
@cheenamalhotra I have installed the latest release for September 2023 and I am finding that this issue persists. Are there any additional steps I need to take to restore this functionality?

**Comment by cheenamalhotra** [comment]
It maybe possible that recent connections are not updated with group info. Could you try any one of the following:
- Editing a recent connection and updating group to desired?
- Selecting Group when selecting a connection?
- Clearing recent connections and allowing list to be recreated after groups are modified?

I noticed the same behavior when working on connections associated with server groups that are later modified - they lose reference to the server group they were part of since the previous group "id" doesn't exist anymore. 
So manually updating group info on recent connections should work as a workaround.

Is there a different use-case you're following?

**Comment by Rob-DeRosia** [comment]
I was planning to test by clearing my recent connections and allowign the list to be recreated, however I cannot seem to get any of the connections I am using to be stored as a "recent connection". My list remains empty (different problem?) so I cannot test this tab color problem yet.

**Comment by jakodev** [comment]
Hi @cheenamalhotra ,

I'm sorry to report you that I've installed the last version and the issue still persists. 

I've cleaned the recent connections list _(btw I've discovered another problem regarding the recent connections that I've already reported)_ and recreated, then I've set the server group in each recent connection manually and at the first click seems work but then, after switching through the recent connections, the problem returns........... please fix this, it's really annoying :(

**Comment by hayryn** [comment]
Hello all,

Maybe I'm doing it wrong, but I'm also not able to get the tab color based on the server group color to work.  Which would be really helpful if it would!  I have both general release 1.46.1 and 1.47.0-insider versions installed on Windows 11 Pro x64, and neither works. 

My understanding of how it should work...
1.  I create a new server group by clicking the 'Add server group' folder icon next to CONNECTION... 
2.  I enter the Server group name, description, and select a color.
3.  I then add a new connection to that server group by clicking the 'New Connection' icon next to my new server group
4.  I then add my server connection details as well as select the new server group in the connection properties...even though it seems like it should be there by default since I clicked 'New Connection' at the server group level.
5.  I then right-click on my desired database from that new connection in that new server group and open a new query.

This should then open a new query tab with that server group color, correct?  It does not.  I have attempted to change the connection and ensured the server group was selected in the connection...and still no joy.

Maybe for some reason it has to do with the connection properties?  I use MS SQL Server connection Type, Windows Authentication, Encrypt Mandatory (True), and Trust server certificate True.

I have also tried the following steps listed by @cheenamalhotra...thanks for the attempt and info by the way!
- I tried editing a recent connection and updating the group to desired.
- I tried selecting Group when selecting a connection.
- And I also tried clearing recent connections and allowing the list to be recreated after groups are modified.

I am currently using the Dark+ theme, but I have switched to other light and dark themes with no luck.  I also created a new profile in case some changed settings may be to blame...also no luck.  However, I'm also assuming when creating a new profile, it uses default settings and nothing is carried over from my default profile.

I've noticed in this thread, and another about this same issue, that some users are able to get it to work sometimes or initially but then it breaks.  For me, I have never gotten it to work at all.  

Any help or guidance would be appreciated!

Thanks!

**Comment by jakodev** [comment]
Hi @cheenamalhotra  ,

I would like to point out that the problem persists even with v1.47
Can you kindly fix it? This problem is really really annoying. Thank you

**Comment by jakodev** [comment]
Hi, @cheenamalhotra @kisantia 

this issue still persists also with the v1.48, just saying...
I beg you, fix it :(

**Comment by stamminator** [comment]
This issue may seem like a small annoyance, but when the user is expecting colorization on actively connected tabs to avoid running dangerous queries against production, this bug becomes a serious risk. This is one of those features which either needs to work completely or shouldn't be used altogether.

Please revisit a fix for this.

**Comment by jakodev** [comment]
Is there any news about this problem? We are now at v1.50 without the fix... Why?

**Comment by stamminator** [comment]
@jakodev I think the problem is that they don't support ADS as a serious product. I've just settled on SSMS + Redgate SQL Prompt for SQL Server and Jetbrains DataGrip for everything else.
