### ISSUE TITLE
Trying to activate Python or PowerShell Kernel failure

### ISSUE THREAD

**Issue by abacrotto** [microsoft/azuredatastudio#26075]
Type: <b>Bug</b>

I am trying to start using PowerShell Kernel in my ADS Notebooks. When I select "PowerShell" in the Kernel combo, ADS goes to a dialog indicating there is the need to install dependencies. Then I follow prompts (I have installed python 3.8.10 that is detected by ADS) but, when y press the "Next" button to install the python packages needed, I get an error:

    stderr: ERROR: Cannot install ipykernel==5.5.5, jupyter==1.0.0, jupyterlab==4.2.6 and notebook because these package versions have conflicting dependencies.
    stderr: 
    stdout: 
    stdout: The conflict is caused by:
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.6 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.5 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.4 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.3 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.2 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.1 depends on ipykernel>=6.5.0
    stdout:     The user requested ipykernel==5.5.5
    stdout:     jupyter 1.0.0 depends on ipykernel
    stdout:     jupyterlab 4.2.0 depends on ipykernel>=6.5.0
    stdout: 
    stdout: To fix this you could try to:
    stdout: 1. loosen the range of package versions you've specified
    stdout: 2. remove package versions to allow pip to attempt to solve the dependency conflict

Azure Data Studio version: azuredatastudio 1.50.0 (49c73a84388731fec941dac8d938345ac16bd470, 2024-11-17T22:41:05.327Z)
OS version: Windows_NT x64 10.0.26100
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
![Image](https://github.com/user-attachments/assets/dddce79a-f5e0-445a-bac0-c2d20142e00c)
![Image](https://github.com/user-attachments/assets/b827412c-532f-4334-9628-5ffdf4a29e4f)

**Comment by DearPeter** [comment]
I have the same issue when try to reinstall notebook dependencies.

**Comment by ssteiner-ballhort** [comment]
Python only works for me after reinstall (also using Python 3.8.10 on Windows 10). It wants me to install the notebook module version 7.2.2 but then doesn't work after I install the new version (currently using version 6.5.6)

**Comment by BlackholeBun** [comment]
Same problem here. Trying to enable either python core or powershell on mac. It looks like Notebook 7.2.2 needs ipykernel>=6.29.5, but ADS is specifying 5.5.5.

**Comment by rsulak8** [comment]
The same issue, ADS reinstalled, fresh installation of Python 3.8.10 following this:

https://learn.microsoft.com/en-us/azure-data-studio/notebooks/notebooks-python-offline-installation

+ rust cargo installed. 

AZD 1.50 still not working with Python in notebooks... 👎

**Comment by abacrotto** [comment]
Should we see the "requirements.txt" file somewhere in our ADS directory so we can lift some of the restrictions?
Does anyone know where the file could be located?


Thanks in advance.
Ariel.

**Comment by cross-apply** [comment]
I am also unable to switch to Python in ADS 1.5. I've tried multiple versions of Python (3.8, 3.10 and 3.12) with the same result. ERROR: Cannot install ipykernel==5.5.5, jupyter==1.0.0 and notebook

**Comment by Bowside** [comment]
Same issue for me, Notebook 7.2.2 needs ipykernel>=6.29.5, but ADS is specifying 5.5.5.

**Comment by dannysnowflake1** [comment]
Is there any workaround to this?  I'm completely blocked from using ADS currently.  ADS crashed and asked me to resupply my python information, and now I can't get into ADS because of the conflicting dependencies issue.

**Comment by lily407** [comment]
Same issue. I have uninstalled and reinstalled, restarted at least a dozen times....

**Comment by sam-nolan-tearfund** [comment]
Same issue. @erpett 1.5.0 appears currently broken due to this because of a bump to the notebook version performed by @gy-mate.
https://github.com/microsoft/azuredatastudio/blame/49c73a84388731fec941dac8d938345ac16bd470/extensions/notebook/src/jupyter/requiredJupyterPackages.ts#L21-L25

**Comment by lily407** [comment]
[Found a workaround someone posted in another ticket for the same issue](https://github.com/microsoft/azuredatastudio/issues/26087)

**Comment by abacrotto** [comment]
I am feeling terribly useless. Can not follow the steps in that workaround. Paths do not match my computer configuration. When I try to install the notebook and ipykernel with 

python.exe -m pip install --user "notebook==6.5.5" "ipykernel==5.5.5" 

I get a ton of errors.

![Image](https://github.com/user-attachments/assets/41ced55e-34a4-4870-a43b-2042c87ae43b)

**Comment by amkorousagi** [comment]
same issue

**Comment by abacrotto** [comment]
> [@sam-nolan-tearfund](https://github.com/sam-nolan-tearfund) I guess all other Python package versions need to be bumped as well (if possible).
> 
> I'm sorry that my PR ([#25899](https://github.com/microsoft/azuredatastudio/pull/25899)) caused the problem—I was trying to fix [another bug](https://github.com/microsoft/azuredatastudio/issues/25327) with it.



One and a half months passed since I issued this incident. You have recognized the problem, but no solution nor new version of ADS has been generated. Can you bump the versions of the packages? Can you tell here what are the files that ADS uses when it tries the installation of the python or powershell kernels (or where to find them so we can change the signatures from "=" (equal to) to ">=" (greater than or equal to)?

Thanks for your help in advance.
Regards.
Ariel.

**Comment by gy-mate** [comment]
> Can you bump the versions of the packages?

@abacrotto I've opened a PR (#26132) for this.

I encourage everyone to test the change I've proposed in order not to run into the same issue again!

**Comment by hyperion14** [comment]
@gy-mate 
Same here! Can´t run ADS on my snapdragon based laptop!
No workaround solves the issue.
The bug is reported an discussed here since a year nearly.

Please fix it. ADS is useless otherwise  

Thx.

**Comment by abacrotto** [comment]
So I tried to find out whether there is a new versión of ADS, but no luck.
How do I take your modifications and install them in my ADZ installation?
Can I download something and patch my current installation or change some files?

Thanks in advancer.
Regards.
Ariel.

**Comment by gy-mate** [comment]
@abacrotto Sure, you can build the app from the `main` branch like this: https://github.com/Microsoft/azuredatastudio/wiki/How-to-Contribute#incremental-build

**Comment by rappakos** [comment]
Same problem here

**Comment by doonhamer5** [comment]
I have the same problem

**Comment by jmhrijdt** [comment]
Is there a date for the update to be released? Can't really do any work now..

**Comment by stephensteiner4** [comment]
I was recently on a call with someone from Microsoft about this issue. They’re aware of the issue but there is no timeline to implement a fix. They’re aware suggested using Visual Studio Code instead: https://code.visualstudio.com/

Alternatively, you can install Azure Data Studio version 1.49.1, but the annoying thing is that you’ll have to re-install that every day you want to use Azure Data Studio.

**Comment by jmhrijdt** [comment]
> I was recently on a call with someone from Microsoft about this issue. They’re aware of the issue but there is no timeline to implement a fix. They suggested using Visual Studio Code instead: https://code.visualstudio.com/
> 
> Alternatively, you can install Azure Data Studio version 1.49.1, but the annoying thing is that you’ll have to re-install that every day you want to use Azure Data Studio.

Alright, will try that. The standalone version could work without the need to re-install every day

**Comment by jmhrijdt** [comment]
> > I was recently on a call with someone from Microsoft about this issue. They’re aware of the issue but there is no timeline to implement a fix. They suggested using Visual Studio Code instead: https://code.visualstudio.com/
> > Alternatively, you can install Azure Data Studio version 1.49.1, but the annoying thing is that you’ll have to re-install that every day you want to use Azure Data Studio.
> 
> Alright, will try that. The standalone version could work without the need to re-install every day

Ok so i have fixed the issue using the standalone version of 1.49.1 which makes it possible to keep using it daily without re-installing. 

Steps i took:

1. Downloaded python 3.8 from https://learn.microsoft.com/en-us/azure-data-studio/notebooks/notebooks-python-offline-installation
2. Add this python version to path
3. install the required dependencies manually using pip
4. Start standalone ADS, it recognized the python version and activated the python notebook kernel without issues 

on a sidenote: I still have the regular new/updated ADS installed as well, but i created a separate user settings folder for the standalone version to avoid any issues.

**Comment by Pookam90** [comment]
> > > I was recently on a call with someone from Microsoft about this issue. They’re aware of the issue but there is no timeline to implement a fix. They suggested using Visual Studio Code instead: https://code.visualstudio.com/
> > > Alternatively, you can install Azure Data Studio version 1.49.1, but the annoying thing is that you’ll have to re-install that every day you want to use Azure Data Studio.
> > 
> > 
> > Alright, will try that. The standalone version could work without the need to re-install every day
> 
> Ok so i have fixed the issue using the standalone version of 1.49.1 which makes it possible to keep using it daily without re-installing.
> 
> Steps i took:
> 
> 1. Downloaded python 3.8 from https://learn.microsoft.com/en-us/azure-data-studio/notebooks/notebooks-python-offline-installation
> 2. Add this python version to path
> 3. install the required dependencies manually using pip
> 4. Start standalone ADS, it recognized the python version and activated the python notebook kernel without issues
> 
> on a sidenote: I still have the regular new/updated ADS installed as well, but i created a separate user settings folder for the standalone version to avoid any issues.

Thanks this is working for me as well

**Comment by WAH19** [comment]
Just updated to 1.51 and getting a new error.  500 internal server error.  I noticed if i open a new notebook and change to kernal to python it works and i can paste code and run.  there error comes up when opening an existing .ipynb file.

**Comment by srallen9-uw** [comment]
We are seeing the same behavior as WAH19.

We are still getting Python and PowerShell Kernels not to load.  This time 500 internal server error.  This is on 3 different computers, clean Azure Data Studio installs.  Tried both the built in ADS python engine and a separate 3.13 python install.  I do notice that if I take the command in terminal window in ADS and run in a separate terminal window (PowerShel 7.5) it runs with some warning, including PyPi management running read-only.  Research indicates there was a problem with a change by httpx 0.28.1 that was fixed in Jupyter_lab 4.3.2.  ADS installs 4.2.7.  Upgrading my install to 4.3.2 makes those warnings disappear, but launching ADS with notebook opens replaces with the older version.  

This locking to an earlier version doesn't seem a great idea because one of problems that prevented downgrading to earlier jupyter was changes to some Microsoft file in an October update that prevented installing an earlier version of pyzmq.

I can open the notebook in Jupyter through a web browser and the kernels load fine.  It's only opening that existing ipynb file in ADS that is the problem.  A new ipynb file doesn't have the problem in ADS.  Migrating some of our rather large scripts with many section to a new file is a lot of work.

**Comment by srallen9-uw** [comment]
Also, what's interesting, copying into a new file only works so long as the file is not saved.  As soon as I save the file, then the 500 Internal Server Error occurs inside ADS.

**Comment by dbaduck** [comment]
I have verified that v1.51 of ADS now installs all the pieces of the PowerShell kernel.  Thanks everyone.

**Comment by rsulak8** [comment]
Natural and expected step... Microsoft gave it up.

https://learn.microsoft.com/en-us/azure-data-studio/whats-happening-azure-data-studio

Vivat Visual Studio Code!
