### ISSUE TITLE
Results are being displayed in 2 tables

### ISSUE THREAD

**Issue by Diganth** [Microsoft/azuredatastudio#3759]
Issue Type: <b>Bug</b>

Azure Data Studio Version: 1.3.9

Open a new query window connected to a DB, and run a single SQL select command to display data from one database table.
The "Results" window has 2 tables showing the same data.

Rerunning the query a second time fixes the issue and I see only one table in the "Results" window.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.81GB (14.08GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.2
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-search|Red|0.2.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@JASM2007 this was an unfortunate regression that shipped as part of the result set streaming work (the feature that enables query results to be displayed progressively while the query is executing).  

The 1.3.9 build took a fix that should reduce the occurrences of this rendering bug, but it can still occur sometimes.  We think the issue is fully resolved in master so I'll post an updated insider build later today to get that fix out.  Sorry for the inconvenience.

**Comment by vidhyasagarreddy** [comment]
Most likely, running the query for second time doesn't fix the issue.

**Comment by kburtram** [comment]
This is fixed in the master (and the latest insiders builds) and the fix will be included in the Feb release planned for this week.
