### ISSUE TITLE
Entire window goes blank

### ISSUE THREAD

**Issue by pcavacas** [microsoft/azuredatastudio#8930]
Azure Data Studio Version: 1.14.1

Steps to Reproduce: Happens intermittently, but frequently.

Usually every few minutes the entire window including the title bar and status bars just goes completely blank (either black if I have dark theme applied or white if white theme applied).

I can click where the title bar is and move the window around.

If I resize the window enough times then it redraws, but doesn't always work when resizing it.

**Comment by dzsquared** [comment]
If you're on Windows or MacOS, this might be the same as #8940 and #8775, which are corrected in the insiders build.

**Comment by kburtram** [comment]
@pcavacas  have you been able to see any pattern when this happens? e.g. running large queries, restoring from minimized state, running low on memory, etc.? Or does this happen apparently randomly? We've had numerous reports of this issue but we still don't have an intern repro to investigate yet.

**Comment by kburtram** [comment]
We think the issue may have been fixed in the latest insiders build, and will be in the Feb release later this week.  Though we still don't have an internal repro to validate.  I'll close this issue as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8775 to consolidate issues a bit.
