### ISSUE TITLE
Azure AD MFA Connection > Timeout issue

### ISSUE THREAD

**Issue by Git-BT-Hub** [microsoft/azuredatastudio#9174]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to Azure SQL Server using Azure AD Account [with MFA]
2. After inactivity for a while, connection is broken and user is NOT notified unless an event/activity is performed like expanding DB object folders or executing new command on Server
3. Often Command execution starts executing with no feedback for few mins, but this experience is variable
4. Only way to restore connection is , to disconnect manually and reconnect

Feature Request:
If User can be notified about AD Token expiry or is forced to authenticate if Token expiry is noticed

**Comment by Git-BT-Hub** [comment]
Looks like my issue is similar to #8965

**Comment by aaomidi** [comment]
This is being resolved by the latest auth work

**Comment by aaomidi** [comment]
Can you verify that this problem doesn't exist in the latest insiders build? 

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master

**Comment by canwaf** [comment]
I know this is closed; however the behaviour continues.

**Comment by aaomidi** [comment]
Yeah after more work in this area I realized this wouldn't be fixed. I'll try to get it done for the next release. Thank you!

**Comment by aaomidi** [comment]
@Git-BT-Hub This should be fixed on insiders, I'm going to close this issue for now but please comment back if you keep seeing this issue in insiders and in future releases (1.18+)

**Comment by robo66** [comment]
@aaomidi  I'm still getting token expired after a period of inactivity in Azure Data Studio -

Login failed for user '<token-identified principal>'. Token is expired.

Version: 1.25.3 (user setup)
Commit: b277eafb8f5328ea26c6edfddd1999292ac27937
Date: 2021-02-09T23:10:35.151Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by dgnsaglam** [comment]
Having the same issue. At times I can execute queries on the database no issues, but when I want to open up a stored procedure to alter it, I get the error. 
Version: 1.25.3
Commit: b277eafb8f5328ea26c6edfddd1999292ac27937
Date: 2021-02-09T23:17:41.828Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by richardtallent** [comment]
I'm still getting this here as well. It is **very annoying**.

Version: 1.35.1 (user setup)
Commit: fab63efd307e54c063c8af03474bbb5d77f5fd11
Date: 2022-03-15T18:03:38.261Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
