### ISSUE TITLE
Notebook: UI edge case -  link not scrolling correctly to corresponding section.

### ISSUE THREAD

**Issue by halerankin** [microsoft/azuredatastudio#9941]
> Note: this bug is an edge case where expected behavior under certain conditions is not acceptable. A prior bug [8428](https://github.com/microsoft/azuredatastudio/issues/8428) solved for many issues encountered with respect to document links.

We are dealing with an edge case when navigating to a section in a notebook. Basically if we add a lot of `<br>` on a code cell and we use the same cell to add an anchor link, there is an issue with the offset and the section is not visible. We noticed that Jupyter notebooks handles this case gracefully, is there a way to replicate the same behavior?

Attached: Notebook file (replace txt extension with ipynb before opening in ADS.)
[Anchors-Sample_ipynb.txt](https://github.com/microsoft/azuredatastudio/files/4471723/Anchors-Sample_ipynb.txt)

Attached: Gif showing behavior.
![anchors](https://user-images.githubusercontent.com/12279161/79158411-2604db00-7d8b-11ea-83f9-f284ebd4e348.gif)

- Azure Data Studio Version: 1.16.0

Steps to Reproduce:

1. Add a lot of `<br>` on a code cell, and use the same cell to add an anchor link.
2. Given the offset (of `<br>`s) , when the anchor link is clicked, the section it links to is not visible.

**Comment by halerankin** [comment]
Issue already fixed with by [8428](https://github.com/microsoft/azuredatastudio/issues/8428)

**Comment by MsSQLGirl** [comment]
@halerankin - 

The offset issue is more severe if the text cell containing the links are somewhere in the middle of a notebook.

File to repro: https://github.com/MsSQLGirl/jubilant-data-wizards/blob/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis/ADSNotebooksDemo.ipynb

In Azure Data Studio, you can simply press Ctrl + O, and paste the raw path
`https://raw.githubusercontent.com/MsSQLGirl/jubilant-data-wizards/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis/ADSNotebooksDemo.ipynb`


![LinkingIssue](https://user-images.githubusercontent.com/6405919/102851192-0c16a000-43d0-11eb-987d-74e2c253a31b.gif)

**Comment by MsSQLGirl** [comment]
I converted the ipynb to readme.md (a markdown file). It looks like the links are working (except for the ones that are referring to other notebook's parts) in Azure Data Studio. 

The readme.md file on GitHub, the links behave as expected (for links that are within the md file). i.e. 

The markdown file is here: 
https://github.com/MsSQLGirl/jubilant-data-wizards/tree/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis 

Note: GitHub Jupyter Notebook Viewer doesn't support linking.

**Comment by MsSQLGirl** [comment]
@halerankin  - is the <br> issue still a problem in the latest insider?

**Comment by halerankin** [comment]
@MsSQLGirl I tested both notebook files in the Insider's Build (v.1.26) and confirm the anchors working as expected!

**Comment by MsSQLGirl** [comment]
Closing this. Fixed by #13926.

**Comment by MsSQLGirl** [comment]
Closing this. Fixed by #13926.
